// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/Content/Content.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    LeftMain: typeof import('./src/components/Main/LeftMain/LeftMain.vue')['default']
    LoadingCom: typeof import('./src/components/Loading/LoadingCom.vue')['default']
    Main: typeof import('./src/components/Main/Main.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    NavBarMsg: typeof import('./src/components/NavBar/NavBarMsg.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    RightMain: typeof import('./src/components/Main/RightMain/RightMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
  }
}
